---
title: "Genome-Wide Association Studies"
format: html
---

# What is a Genome-Wide Association Study?

## Background Information
The human genome is very fascinating! The genome consists of all of a person's DNA, and scientists have been studying it for many years. Across all humans, our DNA is very similar, but there are certain regions on the genome that are known to differ from person to person. These regions are called **genetic variants** and they are useful in studying what makes us genetically different from one another. There are multiple types of genetic variants, but Genome-Wide Association Studies use **Single Nucleotide Variants**, or SNVs, which are single nucleotide changes in the DNA sequence. These genetic variants can give scientists insights into a person's inherited traits, diseases, and ancestry.
\
\
**Genome-Wide Association Studies**, or GWAS are used find genetic variants that are significantly associated with the trait of interest by testing thousands of genetic variants across the entire genome. To test a genetic variant, scientists look at one SNV on the genome of *cases* (people expressing the trait of interest) and *controls* (people without the trait of interest) to declare if the nucleotides at that position are associated with posession of the trait of interest. Once scientists have identified genetic variants that **are** associated with a particular trait of interest, they can observe this genetic variant in new subjects to determine if the subject may have inherited the genes for the trait of interest. This practice can be **life saving** when used in medical contexts because it can provide individuals with a proactive approach to their health before an official diagnosis and ensure that individuals can prepare for the treatment they need.
\
\
The supplementary article [Genome-Wide Association Study of 14,000 Cases of Seven Common Diseases and 3,000 Shared Controls (Nature)](https://www.nature.com/articles/nature05911) was an innovative paper that defined common protocols for implementing GWAS for scientific studies. This paper is a foundation of the GWAS and was made possible by developments in DNA sequencing, allowing the analysis of 500,000 SNVs per individual.

# Implementing a Genome-Wide Association Study

## Big Data (p > n)
As mentioned in the introduction, genetic data is **BIG** data. Since there are more variables than data points in the data set, it is not possible to use multiple linear regression to analyze association of genetic variants and traits of interest. There is a lot of math that can explain why multiple linear regression doesn't work, but for the sake of this content summary, you are spared from that.

## Marginal Regression
Since we are unable to use multiple linear regression on all the data points, we can use a marginal regression that looks at each SNV one at a time. The code will walk you through how to run this marginal regression on xxx individuals. Enjoy!


